import React, { useState } from 'react';
import { createRoot } from 'react-dom/client';
import { BarChart3, CheckCircle2, Clock3, LogIn, Package, TrendingUp } from 'lucide-react';
import './style.css';
import LiveDashboard from './LiveDashboard.jsx';
const API=import.meta.env.VITE_API_URL || 'http://localhost:4000/api';
const demo=[{_id:'ord-1048',customer:{name:'Maya Chen',address:'44 Waverly Place'},total:26.5,status:'Received',createdAt:new Date().toISOString(),items:[{name:'Butter Croissant',quantity:2}]},{_id:'ord-1047',customer:{name:'Jon Bell',address:'8 Park Avenue'},total:18,status:'Baking',createdAt:new Date().toISOString(),items:[{name:'Sourdough Loaf',quantity:1}]},{_id:'ord-1046',customer:{name:'Ava Singh',address:'220 5th Avenue'},total:41,status:'Out for Delivery',createdAt:new Date().toISOString(),items:[{name:'Chocolate Tart',quantity:2}]}];
function Login({onLogin}){const [email,setEmail]=useState('manager@portosbakery.com'),[password,setPassword]=useState('portos-demo'),[error,setError]=useState('');const submit=async(e)=>{e.preventDefault();try{const res=await fetch(`${API}/admin/login`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})});if(!res.ok)throw Error();const data=await res.json();localStorage.setItem('token',data.token);onLogin(data.branch)}catch{setError('Unable to sign in. Check your branch credentials.')}};return <main className="login"><div className="login-art"><span>PORTO'S</span><h1>The bakery<br/><i>behind the scenes.</i></h1><p>Every order deserves a little attention.</p></div><form onSubmit={submit}><div className="admin-mark">PORTO'S / MANAGER PORTAL</div><h2>Welcome back.</h2><p className="muted">Sign in to your branch dashboard.</p><label>Branch email<input value={email} onChange={e=>setEmail(e.target.value)} type="email" /></label><label>Password<input value={password} onChange={e=>setPassword(e.target.value)} type="password" /></label>{error&&<p className="error">{error}</p>}<button className="login-btn">Sign in <LogIn size={16}/></button></form></main>}
function Dashboard({branch}){const [orders,setOrders]=useState(demo),[stats,setStats]=useState({totalOrders:128,revenue:4820,active:3});const update=async(id,status)=>{setOrders(items=>items.map(item=>item._id===id?{...item,status}:item));const token=localStorage.getItem('token');await fetch(`${API}/admin/orders/${id}/status`,{method:'PATCH',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({status})}).catch(()=>{});};return <main className="dashboard"><header><div className="admin-mark">PORTO'S / MANAGER PORTAL</div><div className="location">{branch?.name||'Downtown Bakehouse'} <span>·</span> <button onClick={()=>{localStorage.removeItem('token');location.reload()}}>Sign out</button></div></header><section className="welcome"><div><p className="muted">Thursday, September 4, 2026</p><h1>Good morning, manager.</h1><p className="muted">Here is what is happening at your branch today.</p></div><div className="status"><span></span>Accepting orders <Clock3 size={15}/></div></section><section className="stats"><div><div className="stat-icon orange"><Package size={19}/></div><p>Orders completed</p><strong>{stats.totalOrders}</strong><small>+12.4% this month</small></div><div><div className="stat-icon sage"><TrendingUp size={19}/></div><p>Monthly revenue</p><strong>${stats.revenue.toLocaleString()}</strong><small>+8.6% this month</small></div><div><div className="stat-icon dark"><BarChart3 size={19}/></div><p>Active orders</p><strong>{stats.active}</strong><small>Across all channels</small></div></section><section className="orders"><div className="section-title"><div><p className="muted">Live queue</p><h2>Today's orders</h2></div><button className="filter">All orders⌄</button></div><div className="order-table"><div className="table-head"><span>Order</span><span>Customer</span><span>Items</span><span>Total</span><span>Status</span></div>{orders.map(order=><div className="order-row" key={order._id}><strong>#{order._id.slice(-4)}</strong><span>{order.customer.name}<small>{order.customer.address}</small></span><span>{order.items.map(item=>`${item.quantity} × ${item.name}`).join(', ')}</span><strong>${order.total.toFixed(2)}</strong><select value={order.status} onChange={e=>update(order._id,e.target.value)}><option>Received</option><option>Baking</option><option>Out for Delivery</option><option>Completed</option><option>Cancelled</option></select></div>)}</div></section></main>}
function App(){const [branch,setBranch]=useState(localStorage.getItem('token')?{name:'Downtown Bakehouse'}:null);const signOut=()=>{localStorage.removeItem('token');setBranch(null)};return branch?<LiveDashboard branch={branch} onSignOut={signOut}/>:<Login onLogin={setBranch}/>};createRoot(document.getElementById('root')).render(<App/>);
